name: build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: set up gradle
        uses: gradle/gradle-build-action@v3
      - name: build
        run: ./gradlew build
      - name: upload jar file
        uses: actions/upload-artifact@v2
        with:
          name: gha-study-1.0-SNAPSHOT.jar
          path: build/libs/gha-study-1.0-SNAPSHOT.jar
  test-build:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name : download jar file
        uses : actions/download-artifact@v3
        with:
          name: gha-study-1.0-SNAPSHOT.jar
      - name: test jar
        run: java -jar gha-study-1.0-SNAPSHOT.jar
